### ISSUE TITLE
Json Decode Error for SNKRS

### ISSUE THREAD

**Issue by saoheathcliff** [yasserqureshi1/Sneaker-Monitors#108]
Hey, I just downloaded the monitor, not so sure what this error means. Any help would be greatly appreciated!

Payload delivered successfully, code 204.
Traceback (most recent call last):
  File "C:\Users\harryyeam\Sneaker-Monitors\SNKRS\SNKRSMonitor.py", line 236, in <module>
    monitor()
  File "C:\Users\harryyeam\Sneaker-Monitors\SNKRS\SNKRSMonitor.py", line 187, in monitor
    items = scrape_site(proxy, headers)
  File "C:\Users\harryyeam\Sneaker-Monitors\SNKRS\SNKRSMonitor.py", line 39, in scrape_site
    output = json.loads(html.text)
  File "C:\Users\harryyeam\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\harryyeam\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\harryyeam\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yasserqureshi1** [comment]
Should be sorted with the recent updates
