### ISSUE TITLE
Monitors not functioning properly for me.

### ISSUE THREAD

**Issue by king1267** [yasserqureshi1/Sneaker-Monitors#113]
All Monitors have location changed to US in .env file.

_**SNKRS Monitor**_
I followed the video exactly and changed the env file to fit my priorities and none of the new SNKRS releases are showing up on my discord. With and without keywords.

SNKRSlog says this repeated:

_2021-10-04 19:53:53,375 - root - Successfully scraped SNKRS site
2021-10-04 19:53:54,390 - urllib3.connectionpool - Starting new HTTPS connection (1): api.nike.com:443
2021-10-04 19:53:54,575 - urllib3.connectionpool - https://api.nike.com:443 "GET /product_feed/threads/v2/?anchor=0&count=60&filter=marketplace%28US%29&filter=language%28en%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=exclusiveAccess%28true%2Cfalse%29&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title HTTP/1.1" 200 450163
2021-10-04 19:53:54,666 - urllib3.connectionpool - Starting new HTTPS connection (1): api.nike.com:443
2021-10-04 19:53:54,760 - urllib3.connectionpool - https://api.nike.com:443 "GET /product_feed/threads/v2/?anchor=60&count=60&filter=marketplace%28US%29&filter=language%28en%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=exclusiveAccess%28true%2Cfalse%29&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title HTTP/1.1" 200 422365
2021-10-04 19:53:54,815 - urllib3.connectionpool - Starting new HTTPS connection (1): api.nike.com:443_

**_Snipes Monitor_**
Snipes monitor works and shows shoes in my discord but when I add keywords such as 

_'AirJordan1%AirJordan3%AirJordan4%AirJordan5%AirJordan6%AirJordan7%AirJordan9%AirJordan11%Jordan1%Jordan3%Jordan4%Jordan5%Jordan6%Jordan7%Jordan8%Jordan9%Jordan11%Jordan12%AirJordan12%Jordan%DunkHigh%DunkLow%Dunk' 
or 
Air Jordan 1% Air Jordan 3%Air Jordan 4%Air Jordan 5%Air Jordan 6%Air Jordan 7%Air Jordan 9%Air Jordan 11%Jordan 1%Jordan 3%Jordan 4%Jordan 5%Jordan 6%Jordan 7%Jordan 8%Jordan 9%Jordan 11%Jordan 12%Air Jordan 12%Jordan%Dunk High%Dunk Low%Dunk_

nothing shows up and when something does, if you click the link it pops up in german even though I switched the location in the .env file to US. 

**_Footlocker Monitor_**
I edit the .env file to my specifications and I get this constant error every second. 

_Exception found 'list indices must be integers or slices, not str' - Rotating proxy and user-agent
Traceback (most recent call last):
  File "C:\Users\dnmpl\Downloads\Sneaker-Monitors-master\Footsites\Footlocker\FootlockerUSMonitor.py", line 172, in monitor
    comparitor(item, start)
  File "C:\Users\dnmpl\Downloads\Sneaker-Monitors-master\Footsites\Footlocker\FootlockerUSMonitor.py", line 125, in comparitor
    if not checker(item['sku']):
TypeError: list indices must be integers or slices, not str_

Footlockerlog says this repeated over and over.

_2021-10-04 20:25:19,530 - root - Successfully scraped site
2021-10-04 20:25:19,533 - root - list indices must be integers or slices, not str
2021-10-04 20:25:19,535 - urllib3.connectionpool - Starting new HTTPS connection (1): www.footlocker.com:443
2021-10-04 20:25:19,678 - urllib3.connectionpool - https://www.footlocker.com:443 "GET /category/mens/shoes.html HTTP/1.1" 200 70411_

[SNKRSlog.log](https://github.com/yasserqureshi1/Sneaker-Monitors/files/7282037/SNKRSlog.log)
[Snipeslog.log](https://github.com/yasserqureshi1/Sneaker-Monitors/files/7282039/Snipeslog.log)
[Footlockerlog.log](https://github.com/yasserqureshi1/Sneaker-Monitors/files/7282040/Footlockerlog.log)

**Comment by yasserqureshi1** [comment]
The SNKRS monitor seems like it is working fine

I'll check the Snipes monitor  and make the necessary updates for different regions.

The Footlocker monitor struggles to parse the site. I'll look into this

**Comment by king1267** [comment]
> The SNKRS monitor seems like it is working fine
> 
> I'll check the Snipes monitor and make the necessary updates for different regions.
> 
> The Footlocker monitor struggles to parse the site. I'll look into this

So the SNKRS Monitor doesn't give me errors anymore but nothing posts on my discord server. Anchor 60 Anchor 120 Anchor 180 posts over and over which I saw in the explanation for a different issue is a normal behavior but nothing posts in my discord. How can I fix that?
