### ISSUE TITLE
Supreme Monitor

### ISSUE THREAD

**Issue by singh763173** [yasserqureshi1/Sneaker-Monitors#116]
Updated environments file with just the web hook - is there anything else expected?

`Exception found: Traceback (most recent call last):
  File "SupremeMonitor.py", line 178, in monitor
    get_item_variants(product_item['id'], product_item['name'], start, proxy, headers)
  File "SupremeMonitor.py", line 43, in get_item_variants
    item_variants = rq.get(item_url, headers=headers, proxies=proxy).json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)`

**Comment by xyn23** [comment]
I am having same issue

**Comment by matismrd** [comment]
Same

**Comment by yasserqureshi1** [comment]
The monitor will only work whilst the site is live. I've also now made updates which should sort out any issues you had
