### ISSUE TITLE
Shopify Monitor Error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by king1267** [yasserqureshi1/Sneaker-Monitors#120]
When I run Shopify monitor using DTLR and ShoePalace's URL with /products.json at the end I get this repeated error saying "IndexError: list index out of range"

**To Reproduce**
1. Go to '.env'
2. Replace webhook with "mywebhook", Location to "US", and URL to "https://www.dtlr.com/products.json and another to https://www.shoepalace.com/products.json"
3. Run Shopifymonitor.py
4. Get this error:
Exception found: Traceback (most recent call last):
  File "C:\Users\dnmpl\Downloads\Sneaker-Monitors-master\DTLR\DTLRMonitor.py", line 199, in monitor
    items = scrape_site(CONFIG['URL'], proxy, headers)
  File "C:\Users\dnmpl\Downloads\Sneaker-Monitors-master\DTLR\DTLRMonitor.py", line 52, in scrape_site
    'image': product['images'][0]['src'],
IndexError: list index out of range

**Screenshots**
![bfbbbb](https://user-images.githubusercontent.com/68703715/142745948-1755b27f-c639-45f2-9c26-aa373b47bee9.PNG)

**Desktop (please complete the following information):**
 - OS: [Windiows]
 - Browser [chrome]

**Comment by delamae** [comment]
I imagine this is happening because one of the products in products.json doesn't have an image. To verify this, you can change the url to a products.json of a single product that does have an image, and see if it works then.

**Comment by kacperkwapisz** [comment]
Yes, @delamae is right, the error is shown due to a product not having an image. I will let Yasser know about the issue or even commit a fix for this error.

**Comment by ghost** [comment]
Hey. Did u actually download the monitors. And they worked?

**Comment by yasserqureshi1** [comment]
The monitors have had a major overhaul and several scraper bugs were fixed — please update to the latest version. If this still happens, just comment here and I'll reopen. Thanks for reporting! 🙏
