### ISSUE TITLE
SNKRS Monitor 400 Error

### ISSUE THREAD

**Issue by Yuutokata** [yasserqureshi1/Sneaker-Monitors#134]
If i try to run the SNKRS Monitor it says 
`Traceback (most recent call last):
  File "C:\Users\Leo\Downloads\Monitor\SNKRS\SNKRSMonitor.py", line 255, in <module>
    monitor()
  File "C:\Users\Leo\Downloads\Monitor\SNKRS\SNKRSMonitor.py", line 205, in monitor
    items = scrape_site(proxy=proxy, headers=headers)
  File "C:\Users\Leo\Downloads\Monitor\SNKRS\SNKRSMonitor.py", line 45, in scrape_site
    for item in output['objects']:
KeyError: 'objects'`

and the Response status is 400 (Request validation failed)

**Comment by Yuutokata** [comment]
Oh i fixxed it never mind haha
