### ISSUE TITLE
Exception found: Traceback (most recent call last): ERORR CONTINUES TO POP UP

### ISSUE THREAD

**Issue by Posterboi004** [yasserqureshi1/Sneaker-Monitors#141]
=======================================================
The below Issue continues to pop up when setting up the SNKRS monitor.  
And repeats over and over down the page. 
=======================================================

Exception found: Traceback (most recent call last):
  File "C:\Users\franklinwill0824\sneaker-monitors\monitors\snkrs\monitor.py", line 113, in monitor
    to_discord = locations.standard_api(INSTOCK, LOCATION, LANGUAGE, user_agent, proxy, KEYWORDS, start)
  File "C:\Users\franklinwill0824\sneaker-monitors\monitors\snkrs\locations.py", line 61, in standard_api
    output = json.loads(html.text)
  File "C:\Program Files (x86)\Python39-32\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python39-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python39-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yasserqureshi1** [comment]
This occurs when the page doesn't respond with a JSON doc. It can also occur if you get blocked but this rarely happens with the SNKRS page
