### ISSUE TITLE
Could you please help me figure out what wrong

### ISSUE THREAD

**Issue by airheadhtx** [yasserqureshi1/Sneaker-Monitors#143]
Anyone know what I could be doing wrong?"
![Screenshot (16)](https://user-images.githubusercontent.com/114506580/192573935-8cb7149a-f790-4061-8f9a-22188b842736.png)

**Comment by airheadhtx** [comment]
--- RUNNING ---
python: can't open file 'C:\\Users\\David': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 144, in configure_screen
    monitor = get_monitor(monitor_option)
  File "C:\Users\David Sotelo\Desktop\Sneaker-Monitors-master\Sneaker-Monitors-master\sneaker-monitors\__main__.py", line 69, in get_monitor
    return __monitors__[int(index)].lower()
IndexError: list index out of range

Something went wrong. Please check the input...

**Comment by yasserqureshi1** [comment]
> Anyone know what I could be doing wrong?" ![Screenshot (16)](https://user-images.githubusercontent.com/114506580/192573935-8cb7149a-f790-4061-8f9a-22188b842736.png)

How did you set up the software? How did you configure the monitors?

**Comment by yasserqureshi1** [comment]
Updated monitors shouldnt have this issue
