### ISSUE TITLE
Footlocker US Error starting

### ISSUE THREAD

**Issue by PaLiNYG96** [yasserqureshi1/Sneaker-Monitors#153]
Trying to Run the monitor for US location gives the following error: 

```
Could not load products. Below was the response:
{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAkUsAQbFKaq0ArUSZ4A==&cid=1GFuY0nLTmEk2QQAH39kfuHz0IidfB6nXDxAPAmTPgZfr_ddIT-JHXdn82ViN5BUozcixTfzkghCKqSDYqTaO~Td95sVQtHQtP72oG9lvoBOsWqd_W0krX-2zjH6qvU8&referer=https%3A%2F%2Fwww.footlocker.com%2Fapi%2Fproducts%2Fsearch%3Fquery%3Dmen%26currentPage%3D1%26sort%3DnewArrivals%26pageSize%3D60&hash=A55FBF4311ED6F1BF9911EB71931D5&t=bv&s=41878&e=b917e6a73ebf53c5ebd6904a6811d73193621eb7948152e4efd16eb30879abcb"}
Traceback (most recent call last):
  File "F:\Sneaker-Monitors\monitors\footlocker\monitor.py", line 128, in <module>
    monitor()
  File "F:\Sneaker-Monitors\monitors\footlocker\monitor.py", line 124, in monitor
    time.sleep(float(DELAY))

```
Looks like its being blocked by captcha or geo-blocked.

is there a solution to this or is it dead?

**Comment by PaLiNYG96** [comment]
NVM I was just banned  I guess, Free Proxies included in the project didnt work, had to find my own and add them in the list. All good now. Thanks
