### ISSUE TITLE
json decode error

### ISSUE THREAD

**Issue by infralise123984** [yasserqureshi1/Sneaker-Monitors#158]
Exception found: Traceback (most recent call last):
  File "D:\escritorio\sneaker monitorssss\monitors\snkrs\monitor.py", line 93, in monitor
    to_discord = locations.chile(INSTOCK, LOCATION, LANGUAGE, user_agent, proxy, KEYWORDS, start)
  File "D:\escritorio\sneaker monitorssss\monitors\snkrs\locations.py", line 231, in chile
    output = json.loads(html)
  File "C:\Users\Tokyo-3\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Tokyo-3\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Tokyo-3\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 10 (char 9)

**Comment by yasserqureshi1** [comment]
The monitors have had a major overhaul and several scraper bugs were fixed — please update to the latest version. If this still happens, just comment here and I'll reopen. Thanks for reporting! 🙏
