### ISSUE TITLE
Supreme Issue

### ISSUE THREAD

**Issue by mikehenriquezf** [yasserqureshi1/Sneaker-Monitors#28]
I cannot start this monitor on my local environment, i get this error:

$ python3 SupremeMonitor.py
STARTING MONITOR
Traceback (most recent call last):
  File "/Users/mikehenriquez/Desktop/LECHE-MONITORS/Sneaker-Monitors-master/Supreme/SupremeMonitor.py", line 142, in <module>
    SupremeMonitor(webhook=CONFIG['WEBHOOK'], proxy=CONFIG['PROXY']).monitor()
  File "/Users/mikehenriquez/Desktop/LECHE-MONITORS/Sneaker-Monitors-master/Supreme/SupremeMonitor.py", line 130, in monitor
    stock = self.get_stock()
  File "/Users/mikehenriquez/Desktop/LECHE-MONITORS/Sneaker-Monitors-master/Supreme/SupremeMonitor.py", line 32, in get_stock
    stock = rq.get(url, headers=self.headers, proxies=self.proxy).json()['products_and_categories']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

Im doing something wrong?

**Comment by yasserqureshi1** [comment]
Well that error occurs when there is no data was found. I believe this may occur if there were too many requests made in a short period of time. I've made some changes, please try again with the new updates. If it still doesn't work, please send me the log file and any further details with the issue.
