### ISSUE TITLE
SNKRS Monitor crashes immediatly after start

### ISSUE THREAD

**Issue by francesco-plt** [yasserqureshi1/Sneaker-Monitors#66]
This is console output:

```
> python.exe .\SNKRSMonitor.py
STARTING MONITOR
Payload delivered successfully, code 204.
Traceback (most recent call last):
  File "C:\Users\frapa\snkrs-monitor-configured\Sneaker-Monitors\SNKRS\SNKRSMonitor.py", line 168, in <module>
    monitor()
  File "C:\Users\frapa\snkrs-monitor-configured\Sneaker-Monitors\SNKRS\SNKRSMonitor.py", line 134, in monitor
    items = scrape_site(proxy, headers)
  File "C:\Users\frapa\snkrs-monitor-configured\Sneaker-Monitors\SNKRS\SNKRSMonitor.py", line 36, in scrape_site
    for item in output['objects']:
KeyError: 'objects'
```

**Comment by Thjisio** [comment]
Hi,

Looks like there were not found any objects. Make sure you are using working proxies and are actually monitoring a region that is supported. Check the documentation to see whether yours is supported.
